version: '3.9'

services:
  nextjs-app:
    build: .
    container_name: nextjs-app
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - soty-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: soty-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs-app
    networks:
      - soty-network

networks:
  soty-network:
    driver: bridge
